-- Solo playground paragraph library.
-- Generated by scripts/gen-paragraph-seed.mjs from FALLBACK_PARAGRAPHS.
-- Re-run with: node scripts/gen-paragraph-seed.mjs
-- Run AFTER supabase/schema.sql.

-- Step 1. Dedupe.
-- public.paragraphs has no unique constraint on body, and the seed in schema.sql
-- ends in a bare "on conflict do nothing" that cannot dedupe. If that insert was
-- ever applied twice, the same body exists two or more times and the unique index
-- in step 2 will fail. Collapse duplicates, keeping the oldest row per body.
--
-- matches.paragraph_id is "on delete restrict", so repoint matches at the
-- surviving row before deleting anything.
--
-- Both statements below must order identically ("created_at, id") so that the
-- row the UPDATE repoints to is exactly the row the DELETE keeps.

with ranked as (
  select id, body, row_number() over (partition by body order by created_at, id) as rn
  from public.paragraphs
),
keeper as (
  select id, body from ranked where rn = 1
),
dupe as (
  select id, body from ranked where rn > 1
)
update public.matches m
set paragraph_id = keeper.id
from dupe
join keeper on keeper.body = dupe.body
where m.paragraph_id = dupe.id;

with ranked as (
  select id, row_number() over (partition by body order by created_at, id) as rn
  from public.paragraphs
)
delete from public.paragraphs p
using ranked
where ranked.rn > 1
  and p.id = ranked.id;

-- Step 2. Unique index on body, which is what makes the insert in step 3 idempotent.
create unique index if not exists paragraphs_body_unique on public.paragraphs (body);

-- Step 3. Only insert bodies that are not already stored.
insert into public.paragraphs (category, difficulty, body, estimated_seconds, seed_tag)
select * from (values   ('easy', 'easy', 'Neon keys shimmer under steady hands as two focused players chase the same line of text. Every clean letter moves the duel forward, and every mistake leaves a bright mark on the scoreboard.', 35, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('easy', 'easy', 'Cold morning air settles over the field as the sun clears the treeline. Dew pulls slowly from the grass, birds start one by one, and the whole valley wakes up quieter than it slept.', 34, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('easy', 'easy', 'Onions hit the oil with a hiss and the whole kitchen turns warm. Bread goes golden, stock drops low, and by evening the table smells like someone actually planned their afternoon.', 33, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('medium', 'medium', 'A fair typing match is not won by rushing alone. It rewards calm focus, precise corrections, and the ability to keep pace while pressure rises on the other side of the arena.', 38, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('medium', 'medium', 'Light leaves a distant star in 1929 and arrives eight years later, which is strange until the numbers are laid out. Everything you see tonight already left before you were born.', 38, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('medium', 'medium', 'The race is decided in the final lap, not the first sprint. Runners who hold back early still have legs at the line, and runners who spend everything at the whistle have nothing left to spend.', 42, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('programming', 'medium', 'Readable code and readable typing share the same discipline. Small mistakes compound quickly, but careful structure, clear intent, and steady feedback loops keep the system moving.', 39, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('programming', 'medium', 'A stack trace is a story told backwards. The frame where it broke sits at the very top, and the careless line that started everything waits patiently at the bottom, three hundred lines down.', 41, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('random', 'medium', 'Some matches feel like lightning in a quiet room. The countdown fades, the first character glows, and suddenly two strangers are racing through the exact same thought.', 36, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('random', 'medium', 'Nobody planned the queue. The bakery opens, the rain starts, and suddenly strangers are sharing one umbrella and the same furious opinion about a football match as if they had been waiting all week.', 40, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('hard', 'hard', 'Synchronization matters when milliseconds decide a match. A trustworthy arena validates progress on the server, compares completion, speed, accuracy, and time, then records the result without asking the browser to be honest.', 64, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('hard', 'hard', 'Two surgeons, eleven years apart in training, both reach for the same clamp. Outside, monitors argue with themselves, a nurse counts aloud, and somewhere in the building a train leaves the station on time.', 59, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('hard', 'hard', 'Every distributed system makes a bargain with failure: it accepts that a message will be delayed, duplicated, or lost, then pays for that certainty with retries, idempotency keys, and reconciliation loops nobody remembers agreeing to.', 67, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('programming', 'hard', 'Two transactions grab the same row and one of them waits, silently, on a lock that will not be released until a request which already failed is finally cleaned up. The database is behaving correctly. The bug is a promise nobody cancelled.', 65, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
union all
select * from (values   ('programming', 'hard', 'A type system is a bargain you make with the compiler: prove the shape of your data once and every function downstream is allowed to assume it. Get the proof wrong and the error surfaces three modules away, on somebody else''s Monday.', 63, 'fallback')) as v(category, difficulty, body, estimated_seconds, seed_tag)
on conflict (body) do nothing;
